# Generated by Django 4.1.7 on 2023-03-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.CharField(max_length=40)),
                ('Caracteristicas', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Postear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.CharField(max_length=40)),
                ('Edad', models.CharField(max_length=40)),
                ('Caracteristicas', models.CharField(max_length=100)),
                ('Mensaje', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
